###################################################################
# CapsLockMonitor.ps1
#
# Wayne Lindimore
# wlindimore@gmail.com
# AdminsCache.Wordpress.com
#
# 6-3-13
# NotifyIcon Monitoring CapsLock, Notifies with Balloon and Voice
# v2 - embedded icons
###################################################################
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Speech

# Main Form and Setup
$mainForm = New-Object System.Windows.Forms.form
$global:lastCapsLock = [System.Console]::CapsLock
# Hide Main Form
$mainForm.ShowInTaskbar = $false
$mainForm.WindowState = "minimized"

# Timer Object
$timer = New-Object System.Windows.Forms.Timer
$timer.Interval = 2000 
$timer.add_Tick({CapsLockCheck})
$timer.start()

# NotifyIcon Objects
$notifyIcon= New-Object System.Windows.Forms.NotifyIcon
$contextMenu = New-Object System.Windows.Forms.ContextMenu
$notifyIcon.ContextMenu = $contextMenu
$notifyIcon.Visible = $true
$menuItem1 = New-Object System.Windows.Forms.MenuItem -ArgumentList "Exit"
$contextMenu.MenuItems.Add($menuItem1)

# Add Exit MenuItem
$menuItem1.add_Click({
	$notifyIcon.Visible = $False
	$timer.stop()
	$mainForm.close()
})

# Decode and Set Icons
[string]$upIcon64=@"
AAABAAMAGBgQAAEABADoAQAANgAAABgYAAABAAgAyAYAAAYEAAAYGAAAAQAgAIgJAACWEQAAKAAAABgA
AAAwAAAAAQAEAAAAAAAgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICA
AACAgIAAwMDAAAAA/wAA/wAAAP//AP8AAAD/AP8A//8AAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAIuIgAAAAAAAAAAIuIi3uIAAAAAAAAi4d7mImLiAAAAAAIuJi4iYi4mLAAAAAIeLh3i4vbi4
gAAAC4mHe4/4i4mHsAAAiLi4eP//d4uHiAAAt3iYt///uJi3twAAh7i4e///i4h4mAAAuHiLh///eLe4
uLAAibiPuP//uPiLh4AAuIv/9///iP+Ji4AAi4f///////+4uLAAi3uP//////i4dwAAuHi3/////7h7
iwAAC4uLj///+Le4uAAACLeJuP//uHi4kAAAAIuLi4j4uLi4AAAAAAuLiLi4uLeAAAAAAACLi4uLh7gA
AAAAAAAAuLe4twAAAAAAAAAAAAAAAAAAAAD///8A////AP/B/wD+AH8A+AAfAPAADwDwAAcA4AAHAMAA
AwDAAAMAwAADAMAAAQDAAAEAwAABAMAAAQDAAAMAwAADAOAAAwDgAAcA8AAPAPgAHwD8AD8A/wD/AP//
/wAoAAAAGAAAADAAAAABAAQAAAAAACABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAA
AACAAIAAgIAAAICAgADAwMAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAi4iAAAAAAAAAAAi4iLe4gAAAAAAACLh3uYiYuIAAAAAAi4mLiJiLiYsAAAAA
h4uHeLi9uLiAAAALiYd7j/iLiYewAACIuLh4//93i4eIAAC3eJi3//+4mLe3AACHuLh7//+LiHiYAAC4
eIuH//94t7i4sACJuI+4//+4+IuHgAC4i//3//+I/4mLgACLh////////7i4sACLe4//////+Lh3AAC4
eLf/////uHuLAAALi4uP///4t7i4AAAIt4m4//+4eLiQAAAAi4uLiPi4uLgAAAAAC4uIuLi4t4AAAAAA
AIuLi4uHuAAAAAAAAAC4t7i3AAAAAAAAAAAAAAAAAAAAAP///wD///8A/8H/AP4AfwD4AB8A8AAPAPAA
BwDgAAcAwAADAMAAAwDAAAMAwAABAMAAAQDAAAEAwAABAMAAAwDAAAMA4AADAOAABwDwAA8A+AAfAPwA
PwD/AP8A////ACgAAAAYAAAAMAAAAAEACAAAAAAAQAIAAAAAAAAAAAAAAAEAAAABAAAAAAAAXbL/AFu3
/wBctP8AWrv/AF+5/wBav/8AXr//AGGn/wBiqP8AY67/AGmr/wBuqv8AaK7/AG6t/wBxov8AcKT/AHCq
/wB0qf8Acq3/AHSv/wBhsf8AY7f/AGa1/wBpsv8AbbH/AGi0/wBttf8Aarr/AG25/wBqvf8Abr3/AHCx
/wB2sf8AdbT/AHiz/wB8s/8Acrv/AHa4/wBwvv8AeLn/AHm8/wB8vv8AWsP/AFrF/wBZyf8AX8v/AFnN
/wBdzf8AYcH/AGHE/wBnx/8AacH/AG7B/wBoxf8AZcr/AGbN/wBoyf8Ab8j/AGjN/wBwwf8AccX/AHfG
/wB7x/8Af8T/AHLJ/wBxz/8AdM3/AHvJ/wBj0P8AZdH/AGbU/wBo0f8AaNT/AIC7/wCBwf8AhsD/AITF
/wCEyP8AkMH/ALjb/wC43f8AvOX/ANzy/wD6/f8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQMDCFPAAAA
AAAAAAAAAAAAAAAAACEMISpLSyomDCEAAAAAAAAAAAAAAABPGSohFBAQEBAUFCoZSgAAAAAAAAAAAEsZ
IRAQEBAQEBAQEBAhGSoAAAAAAAAAABkhDBAUFCEqJCEUEBAQFAxLAAAAAAAAHBQMDAwRIVH//1EhDAwM
DAwZAAAAAABODAwMDAwMIf////8hDAwMDAwZHAAAAAAXDBkMGSEZGf////8ZGRkhGRkMFwAAAAAIGRkZ
GRkZGf////8ZGRkZGRkZCQAAAAAJGRk9REQ9Gf////8cPT09HBkZGSoAAAAJHBw1U/9BHP////9BQf9S
PRwcFyYAAAAXHBwc////Qf////9C////NRwcFyYAAAABHDUc////////////////HDUcBU4AAAABNTY1
Nf////////////81NTY1AQAAAAAFNjY2Njb//////////zU2NjY1BAAAAAAABTY2NjU2////////NjY2
NjMGRAAAAAAABjYzMzMzM/////82MzMzMzMGAAAAAAAAAAYzRjM7OzP//zs7OztISAYAAAAAAAAAAAAt
LUhIM0Y7M0Y7O0hGLQAAAAAAAAAAAAAASC1GSUhGSUhIRy0tAAAAAAAAAAAAAAAAAABGLS8vLy8vLwAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AP///wD/wf8A/gB/APgAHwDwAA8A8AAHAOAA
BwDAAAMAwAADAMAAAwDAAAEAwAABAMAAAQDAAAEAwAADAMAAAwDgAAMA4AAHAPAADwD4AB8A/AA/AP8A
/wD///8AKAAAABgAAAAwAAAAAQAIAAAAAABAAgAAAAAAAAAAAAAAAQAAAAEAAAAAAABdsv8AW7f/AFy0
/wBau/8AX7n/AFq//wBev/8AYaf/AGKo/wBjrv8Aaav/AG6q/wBorv8Abq3/AHGi/wBwpP8AcKr/AHSp
/wByrf8AdK//AGGx/wBjt/8AZrX/AGmy/wBtsf8AaLT/AG21/wBquv8Abbn/AGq9/wBuvf8AcLH/AHax
/wB1tP8AeLP/AHyz/wByu/8Adrj/AHC+/wB4uf8Aebz/AHy+/wBaw/8AWsX/AFnJ/wBfy/8AWc3/AF3N
/wBhwf8AYcT/AGfH/wBpwf8AbsH/AGjF/wBlyv8AZs3/AGjJ/wBvyP8AaM3/AHDB/wBxxf8Ad8b/AHvH
/wB/xP8Acsn/AHHP/wB0zf8Ae8n/AGPQ/wBl0f8AZtT/AGjR/wBo1P8AgLv/AIHB/wCGwP8AhMX/AITI
/wCQwf8AuNv/ALjd/wC85f8A3PL/APr9/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAwMIU8AAAAAAAAA
AAAAAAAAAAAAIQwhKktLKiYMIQAAAAAAAAAAAAAAAE8ZKiEUEBAQEBQUKhlKAAAAAAAAAAAASxkhEBAQ
EBAQEBAQECEZKgAAAAAAAAAAGSEMEBQUISokIRQQEBAUDEsAAAAAAAAcFAwMDBEhUf//USEMDAwMDBkA
AAAAAE4MDAwMDAwh/////yEMDAwMDBkcAAAAABcMGQwZIRkZ/////xkZGSEZGQwXAAAAAAgZGRkZGRkZ
/////xkZGRkZGRkJAAAAAAkZGT1ERD0Z/////xw9PT0cGRkZKgAAAAkcHDVT/0Ec/////0FB/1I9HBwX
JgAAABccHBz///9B/////0L///81HBwXJgAAAAEcNRz///////////////8cNRwFTgAAAAE1NjU1////
/////////zU1NjUBAAAAAAU2NjY2Nv//////////NTY2NjUEAAAAAAAFNjY2NTb///////82NjY2MwZE
AAAAAAAGNjMzMzMz/////zYzMzMzMwYAAAAAAAAABjNGMzs7M///Ozs7O0hIBgAAAAAAAAAAAC0tSEgz
RjszRjs7SEYtAAAAAAAAAAAAAABILUZJSEZJSEhHLS0AAAAAAAAAAAAAAAAAAEYtLy8vLy8vAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP/B/wD+AH8A+AAfAPAADwDwAAcA4AAHAMAA
AwDAAAMAwAADAMAAAQDAAAEAwAABAMAAAQDAAAMAwAADAOAAAwDgAAcA8AAPAPgAHwD8AD8A/wD/AP//
/wAoAAAAGAAAADAAAAABACAAAAAAAGAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAADGI/w0xiP9IMYj/fjGI/6IxiP+zMYj/szGI/6gxiP+HMYj/VjGI
/xUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwjP8EMIz/UjCM
/6gwjP+zO5f/s0aj/7NLqP+zS6j/s0ek/7M9mv+zMIz/szCM/68wjP9nMIz/CwAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6P/w0uj/+HLo//s0Gg/7NAlP+zOob/szd//7M1e/+zNXv/szZ9
/7M5hP+zPpD/s0Wi/7Muj/+zLo//mi6P/xkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALpP/CC6T
/5Mukv+zPpT/szaA/7M1fv+zNX7/szV+/7M1fv+zNX7/szV+/7M1fv+zNX7/szV//7M8j/+zMJP/sy6T
/6Quk/8ZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZf/fCyT/7M4i/+zNIH/szSB/7M0gv+zOo7/sz2W
/7M/nP+zPpr/szuT/7M3iv+zNIH/szSB/7M0gf+zNob/sy2S/7Mtl/+WLZf/CAAAAAAAAAAAAAAAAAAA
AAArnf81K5r/szaM/7Mzhf+zM4X/szOG/7M0h/+zOpX/s5vP/7P///+z////s5vN/7M5k/+zNIf/szOG
/7Mzhf+zM4X/szSI/7Mplf+zK53/VgAAAAAAAAAAAAAAAAAAAAAqof+TKoj/szKI/7MyiP+zM4r/szOK
/7Mziv+zNpH/s////7P///+z////s////7M3lP+zM4r/szOK/7Myif+zMoj/szKI/7Mviv+zKZ//qyqh
/w0AAAAAAAAAACmn/yYklv+zMYz/szGM/7Mxjf+zMo7/szKO/7Myjv+zMo7/s////7P///+z////s///
/7M0k/+zMo7/szKO/7Myjv+zMY3/szGM/7MxjP+zIo3/symn/0gAAAAAAAAAACes/1Ieg/+zMJD/szCR
/7Mxk/+zMpb/szKW/7MylP+zMZL/s////7P///+z////s////7Mylv+zMZL/szGS/7Mxkv+zMZL/szCQ
/7MwkP+zIoT/syao/3YAAAAAAAAAACOk/3Ighf+zL5X/szCW/7M1pP+zPq7/s0Ow/7M0of+zMJb/s///
/7P///+z////s////7MzoP+zNqj/szer/7M2p/+zM5//sy+V/7MvlP+zKI3/syGa/5MAAAAAAAAAAB+b
/34ijf+zLpn/sy+a/7M0qv+zzu3/s////7M3s/+zMaL/s////7P///+z////s////7M2r/+zObn/s///
/7Og2/+zM6j/sy+a/7Mumf+zKZP/sx2S/54AAAAAAAAAABuZ/3ofkf+zLZ7/sy2f/7Muo/+z////s///
/7P///+zM7L/s////7P///+z////s////7M2vP+z////s////7P///+zMKf/sy2f/7Mtnv+zJ5j/sxmQ
/5wAAAAAAAAAABmb/2cbkv+zLKP/syyj/7Msov+z////s////7P///+z////s////7P///+z////s///
/7P4/f+z////s////7P///+zLKP/syyj/7Mso/+zIpn/sxiT/4cAAAAAAAAAABmi/z8XlP+zK6j/syun
/7Mrp/+zK6b/s////7P///+z////s////7P///+z////s////7P///+z////s////7Mrpv+zK6f/syun
/7Mrqf+zGJX/sxiZ/18AAAAAAAAAABmu/w0Wmf+vKav/syqr/7Mqqv+zKqn/syqp/7P///+z////s///
/7P///+z////s////7P///+z////syqp/7Mqqv+zKqr/syqs/7Mrrf+zFpn/sxik/ygAAAAAAAAAAAAA
AAAVn/9uFZ//syqx/7Mpr/+zKa7/syit/7Morf+z////s////7P///+z////s////7P///+zKK3/symu
/7Mprv+zKbD/syqy/7Mbpf+zFZ//jwAAAAAAAAAAAAAAAAAAAAAUpf8TFKT/qx6s/7MotP+zKLL/syix
/7Mosf+zJ7D/s////7P///+z////s////7MnsP+zKLH/syiy/7Mos/+zKbb/syW0/7MUpP+zFKT/KgAA
AAAAAAAAAAAAAAAAAAAAAAAAFav/NxWq/7Mjtv+zKbn/syi2/7Motv+zKLX/sye0/7P///+z////syi1
/7Motf+zKLb/syi4/7Mpu/+zKr7/sxWr/7MVqv9YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSw
/04UsP+xHLX/syi//7MnvP+zJ7r/sye5/7Mnuf+zJ7n/sye6/7Mnu/+zKL3/syjA/7Mjvf+zFLD/sxSw
/24AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATtf8zE7T/phOy/7Mlwv+zKMP/syfC
/7Mnwf+zJ8L/syfD/7MoxP+zJ8f/sxS0/7MTtf+vE7T/TgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAE7n/CxO5/2ETuf+oE7j/sxO2/7MUuP+zFrv/sxO3/7MTuP+zE7n/rxO5
/3ATuP8VAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAATvf8EE73/MBO9/0gTvf9lE73/axO9/0gTvf83E7z/DQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA////AP///wD+AH8A+AAfAPAADwDgAAcA4AADAMAAAwDAAAEAgAABAIAAAQCAAAEAgAABAIAA
AQCAAAEAgAABAIAAAQDAAAMAwAADAOAABwDwAA8A+AAfAPwAPwD/AP8AKAAAABgAAAAwAAAAAQAgAAAA
AABgCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAxiP8NMYj/SDGI/34xiP+iMYj/szGI/7MxiP+oMYj/hzGI/1YxiP8VAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMIz/BDCM/1IwjP+oMIz/szuX/7NGo/+zS6j/s0uo
/7NHpP+zPZr/szCM/7MwjP+vMIz/ZzCM/wsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAuj/8NLo//hy6P/7NBoP+zQJT/szqG/7M3f/+zNXv/szV7/7M2ff+zOYT/sz6Q/7NFov+zLo//sy6P
/5ouj/8ZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6T/wguk/+TLpL/sz6U/7M2gP+zNX7/szV+
/7M1fv+zNX7/szV+/7M1fv+zNX7/szV+/7M1f/+zPI//szCT/7Muk/+kLpP/GQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAC2X/3wsk/+zOIv/szSB/7M0gf+zNIL/szqO/7M9lv+zP5z/sz6a/7M7k/+zN4r/szSB
/7M0gf+zNIH/szaG/7Mtkv+zLZf/li2X/wgAAAAAAAAAAAAAAAAAAAAAK53/NSua/7M2jP+zM4X/szOF
/7Mzhv+zNIf/szqV/7Obz/+z////s////7Obzf+zOZP/szSH/7Mzhv+zM4X/szOF/7M0iP+zKZX/syud
/1YAAAAAAAAAAAAAAAAAAAAAKqH/kyqI/7MyiP+zMoj/szOK/7Mziv+zM4r/szaR/7P///+z////s///
/7P///+zN5T/szOK/7Mziv+zMon/szKI/7MyiP+zL4r/symf/6sqof8NAAAAAAAAAAApp/8mJJb/szGM
/7MxjP+zMY3/szKO/7Myjv+zMo7/szKO/7P///+z////s////7P///+zNJP/szKO/7Myjv+zMo7/szGN
/7MxjP+zMYz/syKN/7Mpp/9IAAAAAAAAAAAnrP9SHoP/szCQ/7Mwkf+zMZP/szKW/7Mylv+zMpT/szGS
/7P///+z////s////7P///+zMpb/szGS/7Mxkv+zMZL/szGS/7MwkP+zMJD/syKE/7MmqP92AAAAAAAA
AAAjpP9yIIX/sy+V/7Mwlv+zNaT/sz6u/7NDsP+zNKH/szCW/7P///+z////s////7P///+zM6D/szao
/7M3q/+zNqf/szOf/7Mvlf+zL5T/syiN/7Mhmv+TAAAAAAAAAAAfm/9+Io3/sy6Z/7Mvmv+zNKr/s87t
/7P///+zN7P/szGi/7P///+z////s////7P///+zNq//szm5/7P///+zoNv/szOo/7Mvmv+zLpn/symT
/7Mdkv+eAAAAAAAAAAAbmf96H5H/sy2e/7Mtn/+zLqP/s////7P///+z////szOy/7P///+z////s///
/7P///+zNrz/s////7P///+z////szCn/7Mtn/+zLZ7/syeY/7MZkP+cAAAAAAAAAAAZm/9nG5L/syyj
/7Mso/+zLKL/s////7P///+z////s////7P///+z////s////7P///+z+P3/s////7P///+z////syyj
/7Mso/+zLKP/syKZ/7MYk/+HAAAAAAAAAAAZov8/F5T/syuo/7Mrp/+zK6f/syum/7P///+z////s///
/7P///+z////s////7P///+z////s////7P///+zK6b/syun/7Mrp/+zK6n/sxiV/7MYmf9fAAAAAAAA
AAAZrv8NFpn/rymr/7Mqq/+zKqr/syqp/7Mqqf+z////s////7P///+z////s////7P///+z////s///
/7Mqqf+zKqr/syqq/7MqrP+zK63/sxaZ/7MYpP8oAAAAAAAAAAAAAAAAFZ//bhWf/7Mqsf+zKa//symu
/7Morf+zKK3/s////7P///+z////s////7P///+z////syit/7Mprv+zKa7/symw/7Mqsv+zG6X/sxWf
/48AAAAAAAAAAAAAAAAAAAAAFKX/ExSk/6serP+zKLT/syiy/7Mosf+zKLH/syew/7P///+z////s///
/7P///+zJ7D/syix/7Mosv+zKLP/sym2/7MltP+zFKT/sxSk/yoAAAAAAAAAAAAAAAAAAAAAAAAAABWr
/zcVqv+zI7b/sym5/7Motv+zKLb/syi1/7MntP+z////s////7Motf+zKLX/syi2/7MouP+zKbv/syq+
/7MVq/+zFar/WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUsP9OFLD/sRy1/7Mov/+zJ7z/sye6
/7Mnuf+zJ7n/sye5/7Mnuv+zJ7v/syi9/7MowP+zI73/sxSw/7MUsP9uAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAE7X/MxO0/6YTsv+zJcL/syjD/7Mnwv+zJ8H/syfC/7Mnw/+zKMT/syfH
/7MUtP+zE7X/rxO0/04AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABO5
/wsTuf9hE7n/qBO4/7MTtv+zFLj/sxa7/7MTt/+zE7j/sxO5/68Tuf9wE7j/FQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE73/BBO9/zATvf9IE73/ZRO9
/2sTvf9IE73/NxO8/w0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wD///8A/gB/APgA
HwDwAA8A4AAHAOAAAwDAAAMAwAABAIAAAQCAAAEAgAABAIAAAQCAAAEAgAABAIAAAQCAAAEAwAADAMAA
AwDgAAcA8AAPAPgAHwD8AD8A/wD/AA==
"@
$iconStream=[System.IO.MemoryStream][System.Convert]::FromBase64String($upIcon64)
$iconBmp=[System.Drawing.Bitmap][System.Drawing.Image]::FromStream($iconStream)
$iconHandle=$iconBmp.GetHicon()
$upIcon=[System.Drawing.Icon]::FromHandle($iconHandle)

[string]$downIcon64=@"
AAABAAMAGBgQAAEABADoAQAANgAAABgYAAABAAgAyAYAAAYEAAAYGAAAAQAgAIgJAACWEQAAKAAAABgA
AAAwAAAAAQAEAAAAAAAgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAIAAAACAgACAAAAAgACAAICA
AACAgIAAwMDAAAAA/wAA/wAAAP//AP8AAAD/AP8A//8AAP///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAIuIgAAAAAAAAAAIuIi3uIAAAAAAAAi4d7mImLiAAAAAAIuJi4h7iJi4AAAAAIeLh4j4e4eL
gAAAC4mHi///h7d3sAAAiLi4n///+HuHiAAAt3h7////+Ie3twAAh7i///////uHiwAAuHf///////+L
mIAAibj/+P//v/94i4AAuIuPe///h/i4t4AAi4eLh///uLiJi4AAi3uHuP//iYuLiwAAuIt7i///uLi4
eAAAC3i4eI//iLh7iwAACLh7i4/4uHuLcAAAAIuLeLi4uLh4AAAAAAt4uLh7i4uwAAAAAACLi4uIuJgA
AAAAAAAAuJi7ewAAAAAAAAAAAAAAAAAAAAD///8A////AP/B/wD+AH8A+AAfAPAADwDwAAcA4AAHAMAA
AwDAAAMAwAADAMAAAQDAAAEAwAABAMAAAQDAAAMAwAADAOAAAwDgAAcA8AAPAPgAHwD8AD8A/wD/AP//
/wAoAAAAGAAAADAAAAABAAQAAAAAACABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAA
AACAAIAAgIAAAICAgADAwMAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAi4iAAAAAAAAAAAi4iLe4gAAAAAAACLh3uYiYuIAAAAAAi4mLiHuImLgAAAAA
h4uHiPh7h4uAAAALiYeL//+Ht3ewAACIuLif///4e4eIAAC3eHv////4h7e3AACHuL//////+4eLAAC4
d////////4uYgACJuP/4//+//3iLgAC4i497//+H+Li3gACLh4uH//+4uImLgACLe4e4//+Ji4uLAAC4
i3uL//+4uLh4AAALeLh4j/+IuHuLAAAIuHuLj/i4e4twAAAAi4t4uLi4uHgAAAAAC3i4uHuLi7AAAAAA
AIuLi4i4mAAAAAAAAAC4mLt7AAAAAAAAAAAAAAAAAAAAAP///wD///8A/8H/AP4AfwD4AB8A8AAPAPAA
BwDgAAcAwAADAMAAAwDAAAMAwAABAMAAAQDAAAEAwAABAMAAAwDAAAMA4AADAOAABwDwAA8A+AAfAPwA
PwD/AP8A////ACgAAAAYAAAAMAAAAAEACAAAAAAAQAIAAAAAAAAAAAAAAAEAAAABAAAAAAAAXbL/AFu3
/wBctP8AWrv/AF+5/wBav/8AXr//AGGn/wBiqP8AY67/AGmr/wBuqv8AaK7/AG2t/wBxov8AcKX/AHCq
/wB0qf8Acq3/AHSt/wBhsf8AY7f/AGa1/wBpsv8AbLH/AGi0/wBstf8Aarr/AGy4/wBqvf8Ab77/AHCw
/wB1sf8Ac7b/AHS1/wB4s/8AfLP/AHK6/wB1uf8AcLz/AHW+/wB4uf8Aebz/AHy+/wBaw/8AWsX/AFnJ
/wBfy/8AWc3/AF3N/wBhwf8AYcT/AGfH/wBpwf8AaMX/AGbK/wBmzf8AaMn/AGjN/wBzwP8AdMD/AH/E
/wB7yf8AY9D/AGXR/wBm1P8AaNH/AGjU/wCAu/8AgcH/AIbA/wCExf8AhMj/AJDB/wC43v8AseL/ANru
/wD6/P8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACUMDCFKAAAA
AAAAAAAAAAAAAAAAACEMISxGRiwsDCAAAAAAAAAAAAAAAABKICklFBAQEBAQISwgLAAAAAAAAAAAAEYg
IRAQEBQlFBQQEBAUICkAAAAAAAAAACAhEAwQISxOTiwUEBAUDCBGAAAAAAAAHAwMDAwhKU5OTk4sIQwQ
DAwgAAAAAABJDAwMDCkpTk5OTk5OLCEMDAwMNgAAAAAXICAgKSlOTk5OTk5OTj0pICAMFwAAAAAIICAc
KU5OTk5OTk5OTk49HCAgCAAAAAAJFyAcTk5OTk5OTk5OTk5OKSAXCUYAAAAJHBwcTk5OKU5OTk4pTk5O
HBwcID0AAAAXHBwcS04cHE5OTk4cHE5NHBwcFikAAAABHDYcNhwcNk5OTk4cNiw9Nhw2FkYAAAABNjY2
Nj02Nk5OTk42NjY2NjY2AQAAAAAFNjY2NjY2Nk5OTk42NjY2NjY6BQAAAAAABTo6OjY6Nk5OTk42Ojo6
OjoWPwAAAAAANDQ6Ojo6OkxOTkw6Ojo6Ojk0AAAAAAAAADQ5OTo6Ojo6Ojo6OjpDQzQAAAAAAAAAAAAv
L0NDQzlDQ0NDQ0NDLwAAAAAAAAAAAAAAQy9DQ0NDQ0NDQi8vAAAAAAAAAAAAAAAAAABDMS8xMTExMQAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////AP///wD/wf8A/gB/APgAHwDwAA8A8AAHAOAA
BwDAAAMAwAADAMAAAwDAAAEAwAABAMAAAQDAAAEAwAADAMAAAwDgAAMA4AAHAPAADwD4AB8A/AA/AP8A
/wD///8AKAAAABgAAAAwAAAAAQAIAAAAAABAAgAAAAAAAAAAAAAAAQAAAAEAAAAAAABdsv8AW7f/AFy0
/wBau/8AX7n/AFq//wBev/8AYaf/AGKo/wBjrv8Aaav/AG6q/wBorv8Aba3/AHGi/wBwpf8AcKr/AHSp
/wByrf8AdK3/AGGx/wBjt/8AZrX/AGmy/wBssf8AaLT/AGy1/wBquv8AbLj/AGq9/wBvvv8AcLD/AHWx
/wBztv8AdLX/AHiz/wB8s/8Acrr/AHW5/wBwvP8Adb7/AHi5/wB5vP8AfL7/AFrD/wBaxf8AWcn/AF/L
/wBZzf8AXc3/AGHB/wBhxP8AZ8f/AGnB/wBoxf8AZsr/AGbN/wBoyf8AaM3/AHPA/wB0wP8Af8T/AHvJ
/wBj0P8AZdH/AGbU/wBo0f8AaNT/AIC7/wCBwf8AhsD/AITF/wCEyP8AkMH/ALje/wCx4v8A2u7/APr8
/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJQwMIUoAAAAAAAAA
AAAAAAAAAAAAIQwhLEZGLCwMIAAAAAAAAAAAAAAAAEogKSUUEBAQEBAhLCAsAAAAAAAAAAAARiAhEBAQ
FCUUFBAQEBQgKQAAAAAAAAAAICEQDBAhLE5OLBQQEBQMIEYAAAAAAAAcDAwMDCEpTk5OTiwhDBAMDCAA
AAAAAEkMDAwMKSlOTk5OTk4sIQwMDAw2AAAAABcgICApKU5OTk5OTk5OPSkgIAwXAAAAAAggIBwpTk5O
Tk5OTk5OTj0cICAIAAAAAAkXIBxOTk5OTk5OTk5OTk4pIBcJRgAAAAkcHBxOTk4pTk5OTilOTk4cHBwg
PQAAABccHBxLThwcTk5OThwcTk0cHBwWKQAAAAEcNhw2HBw2Tk5OThw2LD02HDYWRgAAAAE2NjY2PTY2
Tk5OTjY2NjY2NjYBAAAAAAU2NjY2NjY2Tk5OTjY2NjY2NjoFAAAAAAAFOjo6Njo2Tk5OTjY6Ojo6OhY/
AAAAAAA0NDo6Ojo6TE5OTDo6Ojo6OTQAAAAAAAAANDk5Ojo6Ojo6Ojo6OkNDNAAAAAAAAAAAAC8vQ0ND
OUNDQ0NDQ0MvAAAAAAAAAAAAAABDL0NDQ0NDQ0NCLy8AAAAAAAAAAAAAAAAAAEMxLzExMTExAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP/B/wD+AH8A+AAfAPAADwDwAAcA4AAHAMAA
AwDAAAMAwAADAMAAAQDAAAEAwAABAMAAAQDAAAMAwAADAOAAAwDgAAcA8AAPAPgAHwD8AD8A/wD/AP//
/wAoAAAAGAAAADAAAAABACAAAAAAAGAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAADGI/w0xiP9IMYj/fjGI/6IxiP+zMYj/szGI/6gxiP+HMYj/VjGI
/xUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwjP8EMIz/UjCM
/6gwjP+zO5f/s0aj/7NLqP+zS6j/s0ek/7M9mv+zMIz/szCM/68wjP9nMIz/CwAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6P/w0uj/+HLo//s0Gg/7NAlP+zOob/szd//7M1e/+zNXv/szZ9
/7M5hP+zPpD/s0Wi/7Muj/+zLo//mi6P/xkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALpP/CC6T
/5Mukv+zPpT/szaA/7M1fv+zNX7/szuN/7M+k/+zPZL/szqK/7M1fv+zNX7/szV//7M8j/+zMJP/sy6T
/6Quk/8ZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZf/fCyT/7M4i/+zNIH/szSB/7M0gv+zO5P/sz+c
/7P///+z////sz6a/7M5j/+zNIH/szSB/7M0gf+zNob/sy2S/7Mtl/+WLZf/CAAAAAAAAAAAAAAAAAAA
AAArnf81K5r/szaM/7Mzhf+zM4X/szOG/7M6lv+zPJ3/s////7P///+z////s////7M9nf+zOZT/szOG
/7Mzhf+zM4X/szSI/7Mplf+zK53/VgAAAAAAAAAAAAAAAAAAAAAqof+TKoj/szKI/7MyiP+zM4r/szma
/7M7n/+z////s////7P///+z////s////7P///+zPKH/sziY/7Myif+zMoj/szKI/7Mviv+zKZ//qyqh
/w0AAAAAAAAAACmn/yYklv+zMYz/szGM/7Mxjf+zOJ7/szqk/7P///+z////s////7P///+z////s///
/7P///+z////szqm/7M3nP+zMY3/szGM/7MxjP+zIo3/symn/0gAAAAAAAAAACes/1Ieg/+zMJD/szCR
/7M2oP+zOKb/s////7P///+z////s////7P///+z////s////7P///+z////s////7M4qP+zNZ7/szCQ
/7MwkP+zIoT/syao/3YAAAAAAAAAACOk/3Ighf+zL5X/szCW/7Mzn/+z////s////7P///+z+Pv/s///
/7P///+z////s////7P///+z////s////7P///+zNKL/sy+V/7MvlP+zKI3/syGa/5MAAAAAAAAAAB+b
/34ijf+zLpn/sy+a/7Mvmv+z////s////7P///+zL5r/s////7P///+z////s////7Mvmv+z////s///
/7P///+zMJ7/sy+a/7Mumf+zKZP/sx2S/54AAAAAAAAAABuZ/3ofkf+zLZ7/sy2f/7Mtnv+zm9H/s///
/7Mtnv+zLZ7/s////7P///+z////s////7Mtnv+zLZ7/s////7PL5/+zLZ7/sy2f/7Mtnv+zJ5j/sxmQ
/5wAAAAAAAAAABmb/2cbkv+zLKP/syyj/7Msov+zLKL/syyi/7Msov+zLKL/s////7P///+z////s///
/7Msov+zLKL/szin/7Mzpf+zLKP/syyj/7Mso/+zIpn/sxiT/4cAAAAAAAAAABmi/z8XlP+zK6j/syun
/7Mrp/+zK6b/syum/7Mrpv+zK6b/s////7P///+z////s////7Mrpv+zK6b/syum/7Mrpv+zK6f/syun
/7Mrqf+zGJX/sxiZ/18AAAAAAAAAABmu/w0Wmf+vKav/syqr/7Mqqv+zKqn/syqp/7Mqqf+zKqn/s///
/7P///+z////s////7Mqqv+zKqn/syqp/7Mqqv+zKqr/syqs/7Mrrf+zFpn/sxik/ygAAAAAAAAAAAAA
AAAVn/9uFZ//syqx/7Mpr/+zKa7/syit/7Morf+zKK3/s////7P///+z////s////7Morf+zKK3/symu
/7Mprv+zKbD/syqy/7Mbpf+zFZ//jwAAAAAAAAAAAAAAAAAAAAAUpf8TFKT/qx6s/7MotP+zKLL/syix
/7Mosf+zJ7D/s5DX/7P///+z////s5DX/7MnsP+zKLH/syiy/7Mos/+zKbb/syW0/7MUpP+zFKT/KgAA
AAAAAAAAAAAAAAAAAAAAAAAAFav/NxWq/7Mjtv+zKbn/syi2/7Motv+zKLX/sye0/7MntP+zJ7T/syi1
/7Motf+zKLb/syi4/7Mpu/+zKr7/sxWr/7MVqv9YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSw
/04UsP+xHLX/syi//7MnvP+zJ7r/sye5/7Mnuf+zJ7n/sye6/7Mnu/+zKL3/syjA/7Mjvf+zFLD/sxSw
/24AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATtf8zE7T/phOy/7Mlwv+zKMP/syfC
/7Mnwf+zJ8L/syfD/7MoxP+zJ8f/sxS0/7MTtf+vE7T/TgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAE7n/CxO5/2ETuf+oE7j/sxO2/7MUuP+zFrv/sxO3/7MTuP+zE7n/rxO5
/3ATuP8VAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAATvf8EE73/MBO9/0gTvf9lE73/axO9/0gTvf83E7z/DQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA////AP///wD+AH8A+AAfAPAADwDgAAcA4AADAMAAAwDAAAEAgAABAIAAAQCAAAEAgAABAIAA
AQCAAAEAgAABAIAAAQDAAAMAwAADAOAABwDwAA8A+AAfAPwAPwD/AP8AKAAAABgAAAAwAAAAAQAgAAAA
AABgCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAxiP8NMYj/SDGI/34xiP+iMYj/szGI/7MxiP+oMYj/hzGI/1YxiP8VAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMIz/BDCM/1IwjP+oMIz/szuX/7NGo/+zS6j/s0uo
/7NHpP+zPZr/szCM/7MwjP+vMIz/ZzCM/wsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAuj/8NLo//hy6P/7NBoP+zQJT/szqG/7M3f/+zNXv/szV7/7M2ff+zOYT/sz6Q/7NFov+zLo//sy6P
/5ouj/8ZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC6T/wguk/+TLpL/sz6U/7M2gP+zNX7/szV+
/7M7jf+zPpP/sz2S/7M6iv+zNX7/szV+/7M1f/+zPI//szCT/7Muk/+kLpP/GQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAC2X/3wsk/+zOIv/szSB/7M0gf+zNIL/szuT/7M/nP+z////s////7M+mv+zOY//szSB
/7M0gf+zNIH/szaG/7Mtkv+zLZf/li2X/wgAAAAAAAAAAAAAAAAAAAAAK53/NSua/7M2jP+zM4X/szOF
/7Mzhv+zOpb/szyd/7P///+z////s////7P///+zPZ3/szmU/7Mzhv+zM4X/szOF/7M0iP+zKZX/syud
/1YAAAAAAAAAAAAAAAAAAAAAKqH/kyqI/7MyiP+zMoj/szOK/7M5mv+zO5//s////7P///+z////s///
/7P///+z////szyh/7M4mP+zMon/szKI/7MyiP+zL4r/symf/6sqof8NAAAAAAAAAAApp/8mJJb/szGM
/7MxjP+zMY3/szie/7M6pP+z////s////7P///+z////s////7P///+z////s////7M6pv+zN5z/szGN
/7MxjP+zMYz/syKN/7Mpp/9IAAAAAAAAAAAnrP9SHoP/szCQ/7Mwkf+zNqD/szim/7P///+z////s///
/7P///+z////s////7P///+z////s////7P///+zOKj/szWe/7MwkP+zMJD/syKE/7MmqP92AAAAAAAA
AAAjpP9yIIX/sy+V/7Mwlv+zM5//s////7P///+z////s/j7/7P///+z////s////7P///+z////s///
/7P///+z////szSi/7Mvlf+zL5T/syiN/7Mhmv+TAAAAAAAAAAAfm/9+Io3/sy6Z/7Mvmv+zL5r/s///
/7P///+z////sy+a/7P///+z////s////7P///+zL5r/s////7P///+z////szCe/7Mvmv+zLpn/symT
/7Mdkv+eAAAAAAAAAAAbmf96H5H/sy2e/7Mtn/+zLZ7/s5vR/7P///+zLZ7/sy2e/7P///+z////s///
/7P///+zLZ7/sy2e/7P///+zy+f/sy2e/7Mtn/+zLZ7/syeY/7MZkP+cAAAAAAAAAAAZm/9nG5L/syyj
/7Mso/+zLKL/syyi/7Msov+zLKL/syyi/7P///+z////s////7P///+zLKL/syyi/7M4p/+zM6X/syyj
/7Mso/+zLKP/syKZ/7MYk/+HAAAAAAAAAAAZov8/F5T/syuo/7Mrp/+zK6f/syum/7Mrpv+zK6b/syum
/7P///+z////s////7P///+zK6b/syum/7Mrpv+zK6b/syun/7Mrp/+zK6n/sxiV/7MYmf9fAAAAAAAA
AAAZrv8NFpn/rymr/7Mqq/+zKqr/syqp/7Mqqf+zKqn/syqp/7P///+z////s////7P///+zKqr/syqp
/7Mqqf+zKqr/syqq/7MqrP+zK63/sxaZ/7MYpP8oAAAAAAAAAAAAAAAAFZ//bhWf/7Mqsf+zKa//symu
/7Morf+zKK3/syit/7P///+z////s////7P///+zKK3/syit/7Mprv+zKa7/symw/7Mqsv+zG6X/sxWf
/48AAAAAAAAAAAAAAAAAAAAAFKX/ExSk/6serP+zKLT/syiy/7Mosf+zKLH/syew/7OQ1/+z////s///
/7OQ1/+zJ7D/syix/7Mosv+zKLP/sym2/7MltP+zFKT/sxSk/yoAAAAAAAAAAAAAAAAAAAAAAAAAABWr
/zcVqv+zI7b/sym5/7Motv+zKLb/syi1/7MntP+zJ7T/sye0/7Motf+zKLX/syi2/7MouP+zKbv/syq+
/7MVq/+zFar/WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUsP9OFLD/sRy1/7Mov/+zJ7z/sye6
/7Mnuf+zJ7n/sye5/7Mnuv+zJ7v/syi9/7MowP+zI73/sxSw/7MUsP9uAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAE7X/MxO0/6YTsv+zJcL/syjD/7Mnwv+zJ8H/syfC/7Mnw/+zKMT/syfH
/7MUtP+zE7X/rxO0/04AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABO5
/wsTuf9hE7n/qBO4/7MTtv+zFLj/sxa7/7MTt/+zE7j/sxO5/68Tuf9wE7j/FQAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE73/BBO9/zATvf9IE73/ZRO9
/2sTvf9IE73/NxO8/w0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wD///8A/gB/APgA
HwDwAA8A4AAHAOAAAwDAAAMAwAABAIAAAQCAAAEAgAABAIAAAQCAAAEAgAABAIAAAQCAAAEAwAADAMAA
AwDgAAcA8AAPAPgAHwD8AD8A/wD/AA==
"@
$iconStream=[System.IO.MemoryStream][System.Convert]::FromBase64String($downIcon64)
$iconBmp=[System.Drawing.Bitmap][System.Drawing.Image]::FromStream($iconStream)
$iconHandle=$iconBmp.GetHicon()
$downIcon=[System.Drawing.Icon]::FromHandle($iconHandle)

# Inital Load
$capsLock = [System.Console]::CapsLock
if ($capsLock -eq $false) { 
            $notifyIcon.Icon = $downIcon
            $notifyIcon.Text = "CapsLock is Off"
} 
if ($capsLock -eq $true) { 
            $notifyIcon.Icon = $upIcon
            $notifyIcon.Text = "CapsLock is On"
} 

Function CapsLockCheck { 
    $capsLock = [System.Console]::CapsLock
    if ($capsLock -eq $false) { 
        if ($capsLock -ne $global:lastCapsLock) {
            $notifyIcon.Icon = $downIcon
            $notifyIcon.Text = "CapsLock is Off"
            $notifyIcon.BalloonTipText = "CapsLock is Off"
            $notifyIcon.BalloonTipTitle = "CapsLock has Changed"
            $notifyIcon.BalloonTipIcon = "Info"
            $notifyIcon.ShowBalloonTip(10000)
            $spokenText = "Caps Lock is Off"
            $global:lastCapsLock = $capsLock
            VoiceNotification
        } 
    }
    if ($capsLock -eq $true) { 
        if ($capsLock -ne $global:lastCapsLock) {
            $notifyIcon.Icon = $upIcon
            $notifyIcon.Text = "CapsLock is On"
            $notifyIcon.BalloonTipText = "CapsLock is On"
            $notifyIcon.BalloonTipTitle = "CapsLock has Changed"
            $notifyIcon.BalloonTipIcon = "Info"
            $notifyIcon.ShowBalloonTip(10000)
            $spokenText = "Caps Lock is On"
            $global:lastCapsLock = $capsLock
            VoiceNotification
        } 
    }
} # End Function CapsLockCheck

Function VoiceNotification {   
    $Voice = New-Object System.Speech.Synthesis.SpeechSynthesizer 
    $voice.rate = -1
    $voice.volume = 100
    [void] $voice.Speak($spokenText)
} # End Function VoiceNotification

[System.Windows.Forms.Application]::Run($mainForm)