###########################################################
# NoSSaver.ps1
#
# Wayne Lindimore
# wlindimore@gmail.com
# AdminsCache.Wordpress.com
#
# 3-14-15
# Toggles NumLock to Prevent Screensaver
# Runs as System Tray Icon
# WinForms NotifyIcon with Timer
# Base64 Encoded Embedded Icon
###########################################################
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
# Hide Host Console
Add-Type -Name Window -Namespace Console -MemberDefinition '
    [DllImport("Kernel32.dll")]
    public static extern IntPtr GetConsoleWindow();

    [DllImport("user32.dll")]
    public static extern bool ShowWindow(IntPtr hWnd, Int32 nCmdShow);
'
function Hide-Console {
    $consolePtr = [Console.Window]::GetConsoleWindow()
    [void][Console.Window]::ShowWindow($consolePtr, 0)
}
hide-console

# Main Form Object
$mainForm = New-Object System.Windows.Forms.form   
# Hide Main Form Window
$mainForm.ShowInTaskbar = $false
$mainForm.WindowState   = "minimized"

# Timer Object
$Timer          = New-Object System.Windows.Forms.Timer
$Timer.Interval = 30000 
$Timer.add_Tick({sendKeys}) 
$Timer.start()

# 'About' Window Setup
# About Form Object
$aboutForm      = New-Object system.Windows.Forms.Form
$aboutForm.Size = New-Object System.Drawing.Size(250,220) 
$aboutForm.Font = New-Object System.Drawing.Font("Calibri",12,[System.Drawing.FontStyle]::Regular)
$aboutForm.Icon = $Icon
$aboutForm.Text = " About NoSSaver"
$aboutForm.StartPosition = "CenterScreen"
# About Label Object
$aboutLabel          = New-Object System.Windows.Forms.Label
$aboutLabel.font     = new-object system.drawing.font("Calibri",14,[system.drawing.fontstyle]::bold)
$aboutLabel.Location = New-Object System.Drawing.Size(10,10) 
$aboutLabel.Size     = New-Object System.Drawing.Size(220,20) 
$aboutLabel.Text     = "  NoSSaver Script"
# Add About Label to Form
$aboutForm.Controls.Add($aboutLabel) 
# About ListBox Object
$aboutListBox          = New-Object System.Windows.Forms.ListBox 
$aboutListBox.Font     = new-object system.drawing.font("Calibri",11,[system.drawing.fontstyle]::regular)
$aboutListBox.Location = New-Object System.Drawing.Size(16,40) 
$aboutListBox.Size     = New-Object System.Drawing.Size(200,40) 
$aboutListBox.Height   = 100
# Add Info to About ListBox
[void] $aboutListBox.Items.Add("     NoSSaver.ps1")
[void] $aboutListBox.Items.Add("  Prevents the Windows")
[void] $aboutListBox.Items.Add("Screensaver from starting ")
[void] $aboutListBox.Items.Add("  by Wayne Lindimore")
[void] $aboutListBox.Items.Add("adminscache.wordpress.com")
# Add About ListBox to Form
$aboutForm.Controls.Add($aboutListBox) 
# About OK Button Object
$OKButton          = New-Object System.Windows.Forms.Button
$OKButton.Location = New-Object System.Drawing.Size(70,150)
$OKButton.Size     = New-Object System.Drawing.Size(75,23)
$OKButton.Text     = "OK"
$OKButton.Add_Click({$aboutForm.Close()})
# Add About OK Button to Form
$aboutForm.Controls.Add($OKButton)

# NotifyIcon Setup
# Decode and Set Icon
[string]$IconB64=@"
AAABAAQAGBgAAAEAIACICQAARgAAACAgAAABACAAqBAAAM4JAAAQEAAAAQAgAGgEAAB2GgAAFhYAAAEA
IAAQCAAA3h4AACgAAAAYAAAAMAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD//wAA
//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAACAAAAA4AAAATAAAAFQAAABkAAAAZAAAAFQAA
ABMAAAAOAAAACAAAAAMAAAAAAAAAAAAA//8AAP//AAD//wAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAEDY0
Lv82NC7/NjQu/zY0Lv82NC7/NjQu/zY0Lv82NC7/NjQu/zY0Lv82NC7/NjQu/zY0Lv82NC7/AAD//wAA
//8AAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAAAAEElLSMN6fnv/oKek/4GGhP+Eiob/hIqH/4OI
hv9/hYL/eoB9/3V7d/9vdHL/fIJ//2JlY/8AAP//AAD//wAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAFJYVVRTV1X/U1dV/01QTf9maWf/Zmln/2ZpZ/9maWf/Zmln/2ZpZ/9NUE3/U1dV/wAA
//8AAP//AAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4+
Of9ZWVX/Pz86/z8/Ov8/Pzr/Pz86/1lZVf8+Pjn/AAD//wAA//8AAP//AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAjJCNn4SJh/+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WK
iP8AAP//AAD//wAA//+Fioj/hYqI/4WKiP+Gi4n+jJGQngAAAAAAAAAAhYqI/uHj4v/n6en/6Orq/+rs
6//r7e3/7O7u/+3v7//v8PD/8PHx//Hz8v/y9PP/9PX1/wAA//8AAP//AAD///T19f/09fX/9PX1//T1
9f/w8vL/houJ/QAAAAAAAAAAhYqI/+jr6v+Gi4n/09fW/4iMi//X29r/2d3c/9vf3v/e4eD/4OPj/+Ll
5f+eoqH/AAD//wAA//8AAP//PZfz/+vt7f+RlZT/6+3t/5GVlP/29/f/hYqI/wAAAAAAAAAAhYqI/+vt
7P/O0tH/0NTT/9LW1f/U2Nf/1trZ/9nc2//b397/3eDg/9/j4v8AAP//AAD//wAA///o6+r/PZfz/+vt
7f/r7e3/6+3t/+vt7f/3+Pj/hYqI/wAAAAAAAAAAhYqI/+7w8P8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAA//8AAP//AAD//wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/5+vr/hYqI/wAA
AAAAAAAAhYqI//Lz8/8AAAD/Gw8G/9b5//8vGgv/OB4N/0AjD/9IJxH/AAD//wAA//8AAP//Vjkf/1KZ
mf9qtLf/XKSm/0ZKOv9BIw//OB4N/wAAAP/7+/v/hYqI/wAAAAAAAAAAhYqI//X29v8AAAD/IxMI/y0Z
Cv83Hg3/QiQP/0wpEv8AAP//AAD//wAA//9tPBr/Zba3/7ft8f+O2d7/1vT3/5rZ3v9FTD7/QiQP/wAA
AP/8/Pz/hYqI/wAAAAAAAAAAhYqI//X29f8AAAD/JRQJ/zAaC/9EKxn/RygS/wAA//8AAP//AAD//3RD
H/9wWTr/Pbm//2xkSP9xRSP/WW9g/6/f4f9apqj/RiYQ/wAAAP/8/Pz/hYqI/wAAAAAAAAAAhYqI//T1
9f8AAAD/MyQZ/z4rHv+lopz/AAD//wAA//8AAP//cksw/3pQM/+AUzT/glQ0/39SMv94TjD/cEgt/2uv
sP9ptrv/TzMf/wAAAP/7/Pz/hYqI/wAAAAAAAAAAhYqI//T19f8AAAD/Qzkx/6OjoP8AAP//AAD//wAA
//9pTDj/1vn//3RSPP92Uzv/dlI6/3RQN/9vTDX/aEcx/1G2vf9RiYf/TDMj/wAAAP/7+/v/hYqI/wAA
AAAAAAAAhYqI//P19P8AAAD/QDk0/wAA//8AAP//AAD//2FOQf9kUEH/aFJC/2pRQf9rUT//ak89/9b5
//9hRzX/XEQz/y+Rlv9JNyn/QC4h/wAAAP/6+/v/hYqI/wAAAAAAAAAAhYqI//P09P8AAAD/AAD//wAA
//8AAP//WVBJ/11SSv9fUUj/X1BG/15OQv9dSz//Wkg8/1ZDNv9QPzL/Sjkt/0IxJ/85KyH/MCQb/wAA
AP/6+vr/hYqI/wAAAAAAAAAAhYqI//P09P8AAP//AAD//wAA//8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/5+vr/hYqI/wAAAAAAAAAAhYuI/QAA
//8AAP//AAD//+/w7//v8PD/7/Hw//Dx8f/w8vH/8fLx//Hy8v/y8/L/8vPz//P08//z9PT/8/T0//T1
9f/09fX/9fb2//X29v/u8O//houJ/QAAAAAAAAAAAAD//wAA//8AAP//h4yK9oeMivaHjIr2h4yK9oeM
ivaHjIr2h4yK9oeMivaHjIr2h4yK9oeMivaHjIr2h4yK9oeNi/aHjYv2iI2L9oiNi/aIjYv2ipGPlAAA
AAAAAP//AAD//wAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD//wAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAD///wA///4APwAMQDgAAMA4AAHAPgADwD/AB8AgAABAIAAAQCAAAEAgAABAIAA
AQCAAAEAgAABAIAAAQCAAAEAgAABAIAAAQCAAAEAgAABAIAAAQCAAAEAH///AD///wAoAAAAIAAAAEAA
AAABACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA
AAQAAAAGAAAACAAAAAkAAAALAAAADAAAAA0AAAAOAAAADgAAAA4AAAAOAAAADQAAAAwAAAALAAAACQAA
AAgAAAAGAAAABAAAAAEAAAAAAAAAAAAAAAAAAAAAAAD//wAA//8AAAAAAAAAAAAAAAAAAAACAAAABQAA
AAgAAAALAAAADgAAABAAAAATAAAAFQAAABcAAAAZAAAAGgAAABsAAAAbAAAAGwAAABsAAAAaAAAAGQAA
ABcAAAAVAAAAEwAAABAAAAAOAAAACwAAAAgAAAAFAAAAAgAA//8AAP//AAD//wAAAAAAAAAAAAAABAAA
AAcAAAAKAAAADgAAABMAAAAYAAAAHQAAACQAAAApAAAALgAAADEAAAA0AAAANwAAADkAAAA5AAAANwAA
ADQAAAAxAAAALgAAACkAAAAkAAAAHQAAABgAAAATAAAADgAAAAoAAP//AAD//wAA//8AAAAAAAAAAAAA
AAEAAAAFAAAADwAAABYAAAAdPDs2/zw7Nv88Ozb/PDs2/zw7Nv88Ozb/PDs2/zw7Nv88Ozb/PDs2/zw7
Nv88Ozb/PDs2/zw7Nv88Ozb/PDs2/zw7Nv88Ozb/PDs2/zw7Nv8AAAAdAAD//wAA//8AAP//AAAAAQAA
AAAAAAAAAAAABQAAAAsAAAAUAAAAGgAAACI+QD2TWV1Z9pKZlf+do6D/eX16/4mOi/+RmJP/mqGc/52k
n/+an5v/lZyY/4+Vkv+KkIz/g4iE/3uBff9obGn/dXt3/2xxbv9OUk72PkA9kwAA//8AAP//AAD//wAA
AAsAAAAFAAAAAAAAAAAAAAAFAAAACgAAAA8AAAAUAAAAGw0NDShUV1XuWV1b/GBkYvpTV1X/aW1r/2lt
a/9pbWv/aW1r/2lta/9pbWv/aW1r/2lta/9pbWv/aW1r/1NXVf9VWVf6U1dU/FNWVO4AAP//AAD//wAA
//8AAAAPAAAACgAAAAUAAAAAAAAAAAAAAAAAAAABAAAABwAAAAsAAAAPAAAAEzY6OjlHTEl2RkpIeEpM
Sf9sbWv/W11a/1tdWv9bXVr/W11a/1tdWv9bXVr/W11a/1tdWv9sbWv/SkxJ/0ZKSHhHTEl2AAD//wAA
//8AAP//AAAACwAAAAcAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAABAAA
AAcAAAALQEA8/1VWUv9BQj3/QUI9/0FCPf9BQj3/QUI9/0FCPf9BQj3/QUI9/1VWUv9AQDz/AAAACwAA
//8AAP//AAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAISOhBuKj43JhouJ/IWKiP+Fioj/hYqI/4WK
iP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WK
iP8AAP//AAD//wAA//+Fioj/hYqI/4WKiP+Fioj/houJ/IyRjsmEjoQbi4+OwsLGxP3m6Oj/6Orp/+nr
6v/p7Ov/6uzs/+vt7f/s7u3/7e7u/+7v7//u8PD/7/Hw//Dx8f/x8vL/8fPz//P09P/z9fT/9PX1//T1
9f/09fX/AAD//wAA//8AAP//9PX1//T19f/09fX/9PX1//T19f/z9PT/zc/O/Y2Sj8CGi4n85uno/9LW
1f+AhYL/1NjX/4iMi//X29n/2Nzb/9rd3P/b397/3eDf/97h4f/g4+L/4eTk/+Pm5f/k5+f/5ujo/7G1
tP/p6+v/sba0/wAA//8AAP//AAD//ymO9P/r7e3/6+3t/5GVlP/r7e3/kZWU/+vt7f/09fX/h4yK/IWK
iP/p6+v/hYqI/9DV0/+Gi4r/09fW/9XZ2P/W2tn/2Nza/9nd3P/b3t3/3ODf/97h4P/f4uL/4eTj/+Ll
5f/k5+b/lpuZ/+fp6f8AAP//AAD//wAA///r7e3/NKr2/+vt7f/r7e3/6+3t/5GVlP/r7e3/kZWU//b3
9/+Fioj/hYqI//39/f/Q0dD/x8jH/8fIyP/HyMj/yMjI/8jIyP/Iycj/yMnJ/8jJyf/Jycn/ycnJ/8nJ
yf/Jycn/ycrK/8nKyv/Kysr/AAD//wAA//8AAP//ysrK/8rKyv/Kysr/ysrK/8rKyv/Kysr/ysrK/8rK
yv/a2tr//v7+/4WKiP+Fioj/zM7N/wAAAP8PDw7/EA8O/xAQD/8REA//EhEP/xMRD/8UERD/FRIQ/xUS
EP8WExD/FhMR/xcTEf8XFBH/GBQR/wAA//8AAP//AAD//xgUEf8YFBL/GBQR/xcUEv8XFBH/FhMR/xUT
Ef8VExH/FBIR/wAAAP/4+fn/hYqI/4WKiP/Fxsb/DQ0N/w8IA/8VCwX/Gw8G/yISCP8oFQn/LRkK/zMc
DP84Hw3/PSEO/0MlEP9GJhD/SigR/0wqEv8AAP//AAD//wAA//8jkZf/Csfb/wXP5v8Kx9z/Gp2n/zNG
Ov88IA7/Nh4N/zEbC/8rFwr/AAAA//n6+v+Fioj/hYqI/8fIyP8ODg3/FQsF/xsPBv8iEgj/KRYJ/y8a
C/81HQz/PCAO/0EkD/9HJxH/XkMw/1EsE/9WLxT/AAD//wAA//8AAP//CM3k/yja8P9D5fn/T+n8/0jn
+v8t3vT/B8/m/yh0cv8/Ig//OR8N/zMcDP8AAAD/+/v7/4WKiP+Fioj/ysvK/w4ODf8ZDQb/IBEH/ycV
Cf8tGQr/NBwM/zsgDv9CJA//SSgS/2FEMP+49f//bEoy/wAA//8AAP//AAD//wrM4f824vf/NuP3/yzg
9f8y4fb/QOX6/0/p/P9H5/r/DM/l/zFaUv8/Ig//OR8N/wAAAP/8/Pz/hYqI/4WKiP/Ky8v/Dg4N/xsP
Bv8lFwz/KhcK/zEaC/84Hg3/PyIP/0YmEP9NKhL/VC4U/2xKMv8AAP//AAD//wAA//8Zt8T/ANTt/wnN
4/8mrbP/OoqE/zCVlv8LyN3/G9Pn/03p/P875Pj/DcHU/0QlEP88IQ7/AAAA//z8/P+Fioj/hYqI/8rL
yv8ODg3/JRoR/5je5v8zIBT/MhsL/zkfDf9AIw//VDYi/08rEv9VLxT/AAD//wAA//8AAP//cUEd/xe5
xv9LgnT/gU0l/35FHv93QRz/cD0a/2Y7HP8koKf/I9Xp/0/p/P8Gz+b/QDIh/z0hDv8AAAD//Pz8/4WK
iP+Fioj/ycvK/w4NDf8lGRH/NScd/zUjF/86JRb/OiIR/1E8LP+t6fL/XT8p/wAA//8AAP//AAD//2c4
GP9sPhz/ckAc/3ZBHP93QRz/dUAb/3E+Gv9rOhn/ZTcY/1s5Hf8JzOH/Sej7/w7N4v83Qzf/PCAO/wAA
AP/7/Pz/hYqI/4WKiP/Jysr/Dg0N/ygeF/8wIxn/Nycc/z8sH/9GMCH/Ry8d/1xIOP8AAP//AAD//wAA
//9ZMRX/XjQW/2M2F/9nOBj/ckUn/2k6Gf9oORj/ZjgY/2I1F/9dMxb/WDAU/xaywP844/j/BNDo/zwo
Fv84Hg3/AAAA//v8+/+Fioj/hYqI/8nKyf8NDQz/KyId/zEnH/9FOTD/Py8k/0YzJ/9MNyn/AAD//wAA
//8AAP//UDAY/1AsE/9TLRP/Vy8U/1s5IP+Hkoj/XTog/1syFf9ZMBX/Vi8U/1ItE/9OKhL/GqOt/xLY
7/8ZmqP/OB4N/zQdDf8AAAD/+/v7/4WKiP+Fioj/yMrJ/wwNDP8sJiP/NjIv/3qRkf9BOTP/RDUr/wAA
//8AAP//AAD//2NMPv9aQTD/XEEv/1k8KP9iRjL/hpmU/9b4/f+Dl5H/Wzwm/0wrFP9KKhP/RygS/0Un
E/8G1e3/B9Xt/zY3LP84JBb/MR4S/wAAAP/6+/v/hYqI/4WKiP/Iycn/DAwM/zw6OP97l5v/3Pn9/4Gb
nf8AAP//AAD//wAA//9gU0r/uezz/2NRRf9UPzD/Vz8w/1c/Lv9ZSz3/jaKf/1dIOv9TOSj/UTgm/041
JP9KMSH/RC8f/xbF2f8xS0b/NCIW/y0cEv8nGQ7/AAAA//r7+/+Fioj/hYqI/8jJyf8LDAz/LS0t/zc+
Pv+BnqH/AAD//wAA//8AAP//RTky/0c7Mv9eV1D/Szsx/0s6L/9LOi7/TDks/0w4K/9YRjj/STQm/0Yy
JP9EMCL/QS4g/zwpHP83KyH/MSwj/y0eFP8oGhH/IRYN/xwRCv8AAAD/+vr6/4WKiP+Fioj/yMnJ/wsM
DP80NDT/NDQ0/wAA//8AAP//AAD//zw3M/89NjL/PjYx/z82L/9ANi7/QDQs/z8zKv8/Min/PjAm/zwu
JP87LCL/OCkf/zUnHf8yJBr/LiEY/ykdFf8lGRL/HxYO/xoRC/8UDAf/DggE/wAAAP/6+vr/hYqI/4aL
ifzX2Nf/AAAA/wAAAP8AAP//AAD//wAA//8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA//j5
+f+Gi4n8iY6NwsjLyf7x8/L/AAD//wAA//8AAP//8/T0//P09P/09fT/9PX0//T19f/09fX/9fb1//X2
9f/19vb/9fb2//b29v/29/b/9vf3//b39//29/f/9/j3//f49//3+Pj/9/j4//j4+P/4+fj/+Pn5//j5
+f/3+Pj/1NbV/YuRjsCEjoQbio6MyAAA//8AAP//AAD//4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WK
iP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WK
iP+Fioj/hYqI/4aLifyLj47IhI6EGwAAAAAAAP//AAD//wAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA//8AAP//AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD//wAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAADzgAAAAwAAAAYAA
AAGAAAABgAAAAcAAAAP8AAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAj////x////8/////KAAAABAA
AAAgAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA//8AAAAAAAAAAAAAAAA2NC70NjQu/zY0
Lv82NC7/NjQu/zY0Lv82NC7/NjQu/zY0Lv82NC70AAD//wAA//8AAP//AAAAAAAAAAAAAAAANjUvqjY0
Lv82NC7/Z25q/2duav9nbmr/Z25q/zY0Lv82NC7/AAD//wAA//8AAP//AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAANjQu/2duav9TV1X/U1dV/2duav82NC7/AAD//wAA//8AAP//AAAAAAAAAACJjYtuiI2L+IWK
iP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/AAD//wAA//8AAP//hYqI/4iNi/iJjYtuh4yK+N3g
3//l6Of/5+np/+nr6//r7e3/7e/v/+/x8f/y8/P/AAD//wAA//8AAP//8vPz//Lz8//q7Ov/iIyL94WK
iP/m6Oj/1NjX/4mNjP/a3t3/3eDg/+Dj4//j5ub/AAD//wAA//8AAP//6+3t/5GVlP/r7e3/9PX1/4WK
iP+Fioj/6uzr/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/AAAA//f3
9/+Fioj/hYqI/+/w8P8AAAD/DwgD/x0PBv8pFgn/AAD//wAA//8AAP//Z73E/4DR2f9erbL/KS4m/wAA
AP/5+vr/hYqI/4WKiP/09fX/AAAA/yARB//W+f//AAD//wAA//8AAP//TcjS/6Dh5v/S8/b//////1uy
t/8AAAD/+/z8/4WKiP+Fioj/9fb2/wAAAP8qGg//AAD//wAA//8AAP//dkcn/2xqUv97Wzv/YXZm/7vn
6v9/z9b/AAAA//z8/P+Fioj/hYqI//T19f8AAAD/AAD//wAA//8AAP//a047/3RTPP94VTv/dlI5/21L
M/90xMr/W6uw/wAAAP/7+/v/hYqI/4WKiP/09fT/AAD//wAA//8AAP//XVBH/2JSRv9kUUT/1vn//15I
Of9VQDL/NJWc/zc4MP8AAAD/+vv7/4WKiP+Fioj/AAD//wAA//8AAP//AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA//r6+v+Fioj/AAD//wAA//8AAP//8/X0//T19f/19vX/9fb2//b2
9v/29/b/9vf3//f49//4+Pj/+Pn5//n5+f/19vb/h4yL9wAA//8AAP//hYqI/4WKiP+Fioj/hYqI/4WK
iP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/houJ+YmNi27//AAA4AAAAOABAAD4AwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAABYAAAAsAAAAAQAgAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA//8AAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAMAAAAIAAAADgAAABMAAAAVAAAAGQAAABkAAAAVAAAAEwAAAA4AAAAIAAAAAwAA
AAAAAAAAAAD//wAA//8AAP//AAAAAAAAAAAAAAAFAAAAEDY0Lv82NC7/NjQu/zY0Lv82NC7/NjQu/zY0
Lv82NC7/NjQu/zY0Lv82NC7/NjQu/zY0Lv82NC7/AAD//wAA//8AAP//AAAAAAAAAAAAAAAAAAAABQAA
ABBJS0jDen57/6CnpP+BhoT/hIqG/4SKh/+DiIb/f4WC/3qAff91e3f/b3Ry/3yCf/9iZWP/AAD//wAA
//8AAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUlhVVFNXVf9TV1X/TVBN/2ZpZ/9maWf/Zmln/2Zp
Z/9maWf/Zmln/01QTf9TV1X/AAD//wAA//8AAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAD4+Of9ZWVX/Pz86/z8/Ov8/Pzr/Pz86/1lZVf8+Pjn/AAD//wAA//8AAP//AAAAAAAA
AAAAAAAAAAAAAIyQjZ+EiYf/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WKiP+Fioj/hYqI/4WK
iP+Fioj/AAD//wAA//8AAP//hYqI/4WKiP+Fioj/houJ/oyRkJ6Fioj+4ePi/+fp6f/o6ur/6uzr/+vt
7f/s7u7/7e/v/+/w8P/w8fH/8fPy//L08//09fX/AAD//wAA//8AAP//9PX1//T19f/09fX/9PX1//Dy
8v+Gi4n9hYqI/+jr6v+Gi4n/09fW/4iMi//X29r/2d3c/9vf3v/e4eD/4OPj/+Ll5f+eoqH/AAD//wAA
//8AAP//PZfz/+vt7f+RlZT/6+3t/5GVlP/29/f/hYqI/4WKiP/r7ez/ztLR/9DU0//S1tX/1NjX/9ba
2f/Z3Nv/29/e/93g4P/f4+L/AAD//wAA//8AAP//6Ovq/z2X8//r7e3/6+3t/+vt7f/r7e3/9/j4/4WK
iP+Fioj/7vDw/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAD//wAA//8AAP//AAAA/wAA
AP8AAAD/AAAA/wAAAP8AAAD/AAAA//n6+v+Fioj/hYqI//Lz8/8AAAD/Gw8G/9b5//8vGgv/OB4N/0Aj
D/9IJxH/AAD//wAA//8AAP//Vjkf/1KZmf9qtLf/XKSm/0ZKOv9BIw//OB4N/wAAAP/7+/v/hYqI/4WK
iP/19vb/AAAA/yMTCP8tGQr/Nx4N/0IkD/9MKRL/AAD//wAA//8AAP//bTwa/2W2t/+37fH/jtne/9b0
9/+a2d7/RUw+/0IkD/8AAAD//Pz8/4WKiP+Fioj/9fb1/wAAAP8lFAn/MBoL/0QrGf9HKBL/AAD//wAA
//8AAP//dEMf/3BZOv89ub//bGRI/3FFI/9Zb2D/r9/h/1qmqP9GJhD/AAAA//z8/P+Fioj/hYqI//T1
9f8AAAD/MyQZ/z4rHv+lopz/AAD//wAA//8AAP//cksw/3pQM/+AUzT/glQ0/39SMv94TjD/cEgt/2uv
sP9ptrv/TzMf/wAAAP/7/Pz/hYqI/4WKiP/09fX/AAAA/0M5Mf+jo6D/AAD//wAA//8AAP//aUw4/9b5
//90Ujz/dlM7/3ZSOv90UDf/b0w1/2hHMf9Rtr3/UYmH/0wzI/8AAAD/+/v7/4WKiP+Fioj/8/X0/wAA
AP9AOTT/AAD//wAA//8AAP//YU5B/2RQQf9oUkL/alFB/2tRP/9qTz3/1vn//2FHNf9cRDP/L5GW/0k3
Kf9ALiH/AAAA//r7+/+Fioj/hYqI//P09P8AAAD/AAD//wAA//8AAP//WVBJ/11SSv9fUUj/X1BG/15O
Qv9dSz//Wkg8/1ZDNv9QPzL/Sjkt/0IxJ/85KyH/MCQb/wAAAP/6+vr/hYqI/4WKiP/z9PT/AAD//wAA
//8AAP//AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAA
AP8AAAD/+fr6/4WKiP+Fi4j9AAD//wAA//8AAP//7/Dv/+/w8P/v8fD/8PHx//Dy8f/x8vH/8fLy//Lz
8v/y8/P/8/Tz//P09P/z9PT/9PX1//T19f/19vb/9fb2/+7w7/+Gi4n9AAD//wAA//8AAP//h4yK9oeM
ivaHjIr2h4yK9oeMivaHjIr2h4yK9oeMivaHjIr2h4yK9oeMivaHjIr2h4yK9oeNi/aHjYv2iI2L9oiN
i/aIjYv2ipGPlAAA//8AAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///AA+ABgAMAABADAAAwA8AAcAP4A
PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAA///wA
"@
$Iconstream = [System.IO.MemoryStream][System.Convert]::FromBase64String($IconB64)
$Iconbmp    = [System.Drawing.Bitmap][System.Drawing.Image]::FromStream($Iconstream)
$Iconhandle = $Iconbmp.GetHicon()
$Icon       = [System.Drawing.Icon]::FromHandle($Iconhandle)
# NotifyIcon Objects
$NotifyIcon  = New-Object System.Windows.Forms.NotifyIcon
$ContextMenu = New-Object System.Windows.Forms.ContextMenu
$NotifyIcon.ContextMenu = $ContextMenu
$NotifyIcon.Icon = $Icon
$NotifyIcon.Visible = $True
$NotifyIcon.Text = "NoSSaver"
$MenuItem1 = New-Object System.Windows.Forms.MenuItem -ArgumentList "About..."
$MenuItem2 = New-Object System.Windows.Forms.MenuItem -ArgumentList "Exit"
# Add Context MenuItems
[void] $contextMenu.MenuItems.Add($MenuItem1)
[void] $contextMenu.MenuItems.Add($MenuItem2)
# Add 'About' MenuItem
$MenuItem1.add_Click({
    [void] $aboutForm.ShowDialog() 
})
# Add Exit MenuItem
$MenuItem2.add_Click({
	$Timer.stop()
	$NotifyIcon.Visible = $False
	$mainForm.close()
})

Function sendKeys() {           
    $shell = New-Object -com "Wscript.Shell"
    $shell.sendkeys(“{NumLock}{NumLock}”)
    $shell.Dispose
}

[void][System.Windows.Forms.Application]::Run($mainForm)   # Run Main Form to Initiate NotifyIcon